version: '3.7'

services:
  database_rental:
    image: postgres
    container_name: database_rental
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres

      
  app:
    build: .
    container_name: rentalx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_rental
    depends_on:
      - database_rental

volumes:
  pgdata:
    driver: local